production:
  attachments_storage: s3
  s3_endpoint: storage.googleapis.com
  s3_bucket: <%= ENV['GCS_BUCKET_NAME'] %>
  s3_access_key_id: <%= ENV['GCS_ACCESS_KEY_ID'] %>
  s3_secret_access_key: <%= ENV['GCS_SECRET_ACCESS_KEY'] %>
  s3_region: asia-northeast1

  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: <%= ENV.fetch('SMTP_ADDRESS', 'smtp-relay.gmail.com') %>
      port: <%= ENV.fetch('SMTP_PORT', '587') %>
      authentication: :plain
      domain: <%= ENV['SMTP_DOMAIN'] %>
      user_name: <%= ENV['SMTP_USER'] %>
      password: <%= ENV['SMTP_PASSWORD'] %>
      enable_starttls_auto: true
