production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
